import { Lead, Activity, ChatMessage, Task } from "./types";

export const leads: Lead[] = [
  {
    id: "LD-001",
    name: "María González",
    company: "TechCorp Ecuador",
    email: "maria.gonzalez@techcorp.ec",
    phone: "+593 99 234 5678",
    source: "Website Form",
    planInterest: "Plan Corporativo Premium",
    stage: "Qualified",
    qualScore: 85,
    qualLevel: "High",
    assignedTo: "Carlos Mendoza",
    createdAt: "2026-02-10",
    lastContact: "2026-02-22",
  },
  {
    id: "LD-002",
    name: "Roberto Espinoza",
    company: "Grupo Financiero Andes",
    email: "r.espinoza@gfandes.com",
    phone: "+593 98 876 5432",
    source: "Broker Referral",
    planInterest: "Plan Familiar Plus",
    stage: "Contacted",
    qualScore: 62,
    qualLevel: "Medium",
    assignedTo: "Ana Ruiz",
    createdAt: "2026-02-14",
    lastContact: "2026-02-20",
  },
  {
    id: "LD-003",
    name: "Lucía Paredes",
    company: "Farmacéutica Nacional",
    email: "lucia.paredes@farmanac.ec",
    phone: "+593 97 111 2233",
    source: "Trade Show",
    planInterest: "Plan Individual Básico",
    stage: "New",
    qualScore: 45,
    qualLevel: "Low",
    assignedTo: "Carlos Mendoza",
    createdAt: "2026-02-22",
    lastContact: "",
  },
  {
    id: "LD-004",
    name: "Andrés Villacís",
    company: "Constructora Quito S.A.",
    email: "a.villacis@cqsa.ec",
    phone: "+593 96 555 7788",
    source: "LinkedIn",
    planInterest: "Plan Corporativo Estándar",
    stage: "Won",
    qualScore: 92,
    qualLevel: "High",
    assignedTo: "Ana Ruiz",
    createdAt: "2026-01-28",
    lastContact: "2026-02-18",
  },
  {
    id: "LD-005",
    name: "Sofía Cevallos",
    company: "Importadora del Pacífico",
    email: "s.cevallos@impacific.com",
    phone: "+593 99 888 4455",
    source: "WhatsApp Inbound",
    planInterest: "Plan Familiar Premium",
    stage: "Contacted",
    qualScore: 71,
    qualLevel: "Medium",
    assignedTo: "Carlos Mendoza",
    createdAt: "2026-02-16",
    lastContact: "2026-02-21",
  },
  {
    id: "LD-006",
    name: "Diego Ramírez",
    company: "Automotriz Sierra",
    email: "d.ramirez@autosierra.ec",
    phone: "+593 98 333 6677",
    source: "Website Form",
    planInterest: "Plan Corporativo Premium",
    stage: "New",
    qualScore: 38,
    qualLevel: "Low",
    assignedTo: "Ana Ruiz",
    createdAt: "2026-02-23",
    lastContact: "",
  },
  {
    id: "LD-007",
    name: "Carmen Aguirre",
    company: "Textiles Montecristi",
    email: "c.aguirre@texmontecristi.ec",
    phone: "+593 97 222 9900",
    source: "Broker Referral",
    planInterest: "Plan Individual Plus",
    stage: "Qualified",
    qualScore: 78,
    qualLevel: "High",
    assignedTo: "Carlos Mendoza",
    createdAt: "2026-02-08",
    lastContact: "2026-02-23",
  },
];

export const activities: Activity[] = [
  { id: "A1", leadId: "LD-001", type: "note", title: "Lead captured", description: "María submitted the corporate plan inquiry form on saludsa.com", date: "2026-02-10T09:15:00" },
  { id: "A2", leadId: "LD-001", type: "call", title: "Initial outreach call", description: "Spoke with María for 12 min. She manages benefits for 50 employees. Very interested in premium corporate plan.", date: "2026-02-12T10:30:00" },
  { id: "A3", leadId: "LD-001", type: "email", title: "Sent plan comparison PDF", description: "Emailed corporate plan brochure and pricing comparison for 50+ employee groups.", date: "2026-02-13T14:00:00" },
  { id: "A4", leadId: "LD-001", type: "chat", title: "WhatsApp follow-up", description: "María asked about dental coverage add-on. Confirmed it's included in Premium tier.", date: "2026-02-18T11:20:00" },
  { id: "A5", leadId: "LD-001", type: "meeting", title: "Virtual presentation", description: "Presented full corporate plan details to María and HR director. They will review with finance team.", date: "2026-02-20T15:00:00" },
  { id: "A6", leadId: "LD-001", type: "task", title: "Follow-up email scheduled", description: "Send proposal document and ROI analysis by Feb 25.", date: "2026-02-25T09:00:00", completed: false },
];

export const chatMessages: ChatMessage[] = [
  { id: "C1", sender: "agent", text: "¡Hola María! Soy Carlos de Saludsa. Recibimos tu solicitud sobre nuestro Plan Corporativo Premium. ¿Tienes unos minutos para conversar?", time: "10:30 AM" },
  { id: "C2", sender: "lead", text: "¡Hola Carlos! Sí, claro. Estamos buscando un plan de salud para nuestros 50 empleados.", time: "10:32 AM" },
  { id: "C3", sender: "agent", text: "Perfecto. El Plan Corporativo Premium incluye cobertura médica completa, dental, y acceso a nuestra red de más de 2,000 especialistas. ¿Les interesa también la cobertura internacional?", time: "10:33 AM" },
  { id: "C4", sender: "lead", text: "Sí, tenemos empleados que viajan frecuentemente. ¿Qué cobertura tienen fuera del país?", time: "10:35 AM" },
  { id: "C5", sender: "agent", text: "Excelente pregunta. El plan Premium incluye cobertura de emergencias internacionales hasta $500,000. También ofrecemos un add-on de cobertura internacional completa. Te envío el detalle por correo.", time: "10:36 AM" },
  { id: "C6", sender: "lead", text: "Perfecto, me interesa mucho. ¿Podemos agendar una reunión con nuestro director de RRHH esta semana?", time: "10:38 AM" },
  { id: "C7", sender: "agent", text: "¡Por supuesto! ¿Les funciona el jueves a las 3pm? Puedo hacer una presentación virtual con toda la información.", time: "10:39 AM" },
  { id: "C8", sender: "lead", text: "El jueves a las 3pm está perfecto. Te confirmo por correo. ¡Gracias Carlos!", time: "10:41 AM" },
];

export const tasks: Task[] = [
  { id: "T1", leadId: "LD-001", leadName: "María González", title: "Send proposal document", dueDate: "2026-02-25", completed: false, type: "email" },
  { id: "T2", leadId: "LD-002", leadName: "Roberto Espinoza", title: "Follow-up call on family plan", dueDate: "2026-02-24", completed: false, type: "call" },
  { id: "T3", leadId: "LD-005", leadName: "Sofía Cevallos", title: "Schedule product demo", dueDate: "2026-02-24", completed: false, type: "meeting" },
  { id: "T4", leadId: "LD-007", leadName: "Carmen Aguirre", title: "Send broker referral bonus info", dueDate: "2026-02-24", completed: true, type: "email" },
  { id: "T5", leadId: "LD-001", leadName: "María González", title: "Prepare ROI analysis", dueDate: "2026-02-25", completed: false, type: "email" },
];

export const pipelineData = [
  { stage: "New", count: 2, color: "hsl(217, 91%, 50%)" },
  { stage: "Contacted", count: 2, color: "hsl(38, 92%, 50%)" },
  { stage: "Qualified", count: 2, color: "hsl(262, 83%, 58%)" },
  { stage: "Won", count: 1, color: "hsl(142, 71%, 45%)" },
];
